### ISSUE TITLE
How to combine the skill volcanic ashes with bloodlust?

### ISSUE THREAD

**Issue by ArlequinaMorow** [SpenceKonde/AzzyAI#9]
Hey, i need help for make the dieter use bloodlust when he cast volcanic ashes.
thx

**Comment by SpenceKonde** [comment]
No special steps should be necessary, other than setting it to use both bloodlust and ash... Note that I no longer play RO and am not actively maintaining this AI, though I will happily merge PRs.

**Comment by ArlequinaMorow** [comment]
Okay .. I do not understand much of Lua or C, but I'm studying about .. could you give me a hint of some material? My goal is to make the azzyai combine the skills of homunculus .. for now ashes bloodlusty ... but I have no idea where to start ..
The only thing I found out about this was this:
Https://forums.warpportal.com/index.php?/topic/136823-dieter-skills-ai/?p=2546676
thank you.

**Comment by ArlequinaMorow** [comment]
elseif htype==DIETER and UseDieterLavaSlide==1 and LavaSlideMode==0 then
skill=MH_LAVA_SLIDE
if DieterLavaSlideLevel==nil then
level=5
else
level=DieterLavaSlideLevel
end
end 
if AutoSkillCooldown[skill]~=nil then
if GetTick() < AutoSkillCooldown[skill] then -- in cooldown
level=0
skill=0
end
end
end

elseif  (homuntype==2) then --it's an amistr
skill=HAMI_BLOODLUST
level=3
end

elseif (htype==DIETER and UseDieterVolcanicAsh==1 and VolcanicAshMode~=0) then
skill=MH_VOLCANIC_ASH
level = 5
skillopt=VolcanicAshMode
end


I find this in AzzyAI.. but how I combine bloodlust with volcanic ash or lava slide?

**Comment by ArlequinaMorow** [comment]
How I write the code.. if dieters spell lavaslide.. else spell bloodlust..
When homunculus cast any skill the RO don't read AI? 
Can I make homunculus combine skill with azzyai? Or I need use other away..?
Sorry for all.. but help meeeeeee. . sz

**Comment by SpenceKonde** [comment]
Lavaslide + bloodlust already works - It's not really clear to me what the behavior you want is precisely. And as I mentioned, I no longer play RO so I don't remember exactly what the state of the AI was when I left w/regards to these skills. Also, are you talking ash or lavaslide? And casting the ground target skill under owner's feet, or on the target?

**Comment by ArlequinaMorow** [comment]
I speak about lava slide.. spell in owner. But I want to know how I make for dieter spell bloodlust when casting lava slide.
For example.. I use manually lava slide and hen he casting lava slide I use manually bloodlust.. and he combine the two skill and don'the take the cooldown of bloodlust.. but I want to make this automatically...

**Comment by ArlequinaMorow** [comment]
Sorry for close and reopen.. but I use my cellphone and I use "comment button" and don't go.. =/

**Comment by SpenceKonde** [comment]
OH, the exploit where you can bypass the after cast delay - that still works?! I thought that had been fixed. 

In any event, it is not possible to make the AI do that. While the homun is doing the casting animation, the game does not call the AI loop, so the AI can't take any actions during that time.

**Comment by ArlequinaMorow** [comment]
can you see this video?
https://www.youtube.com/watch?v=Wh-tR25E3Zs&t=117s
i play in bRO and here.. we have this bug yet.. and this guy can make azzyai use this bug.. but he stop play and don't have your azzyai config... after this video can you say to me, that is not possible to make in azzyai? if is impossible i will stop search for this.... if you say.. this is possible... i will search every day for anything about this and make this.. =^.^=

**Comment by SpenceKonde** [comment]
Did you read what I wrote? 
> In any event, it is not possible to make the AI do that. While the homun is doing the casting animation, the game does not call the AI loop, so the AI can't take any actions during that time.

I know the bug you mean, we had it on iRO. I tried to make my homun abuse it back when I played, because everyone was begging for it. I was not successful - the AI just plain doesn't get called during the window of time it would need to use bloodlust; the game stops calling AI() while there's a cast bar. 

You can use it manually because manually using a self-targeted skill bypasses the AI entirely.

**Comment by idreus** [comment]
The guy from the video who Arlequina just posted, used combos, (CBC, EQC) configs for use mutiple skills in order to use the bug with Volcanic Ash + Bloodlust or LavaSlide + MagmaFlow. I research, write and rewrited a lot of codes from azzy AI trying do change eleanor skills and trigers to DIETER skills in the lines who are used for combos (set by homunculus tatics) and i just cant figure out how to do it works.... I'm very frustrated, i'm not a programer, but i just studied for almost twelve hours straight, and i just cant believe i'm not able to do it. Very sad, if the guy even given us a clue, but he said he will not help us with this. I just want to use Volcanic Ash and surpass the delay using bloodlust during his cast (as Arlequina said) but i just don't have the knowledge to edit Eleanor combos in order to make this "combos" for dieter. Sadly...

**Comment by SpenceKonde** [comment]
I do not pley RO nor do I have any recent information on it.
